### ISSUE TITLE
Impossible to sign up. Confirmation link doesn't work

### ISSUE THREAD

**Issue by albanlv** [nukomeet/coworfing#351]
The confirmation link doesn't work
![zrzut ekranu 2014-08-21 o 13 10 58](https://cloud.githubusercontent.com/assets/845176/3998361/2e4efd02-2947-11e4-8ac5-a142acf8356d.png)

**Comment by whoshallsucceed** [comment]
@albanlv Should be okay now ;)

**Comment by albanlv** [comment]
And it does work! Kudos
